### ISSUE TITLE
Minimize to Tray when Game is Run

### ISSUE THREAD

**Issue by AskaLangly** [BuIlDaLiBlE/BetterHI3Launcher#1]
When I run the launcher via Steam, it tells others that I'm playing the game, but when I click Start on the launcher, it closes completely, therefore I'm running HI3, but Steam says I'm just online. I suggest to _add an option to minimize to the system tray when the program is started_, so that I can let my Steam friends know that I'm playing HI3.

**Comment by BuIlDaLiBlE** [comment]
Actually, I was thinking about this from the start. Originally I made it close so that it doesn't hang around unupdated (and with old metadata) but that's become less relevant by now. Thanks for the suggestion, will change the behavior with the next update.

**Comment by BuIlDaLiBlE** [comment]
Addressed in e3de18e
