### ISSUE TITLE
New option

### ISSUE THREAD

**Issue by KorewaLidesu** [BuIlDaLiBlE/BetterHI3Launcher#10]
**Is your feature request related to a problem? Please describe.**
Add option to open data/cache folder

**Describe the solution you'd like**
This option will open data/cache folder so user can add/update manually themselves.

**Describe alternatives you've considered**
<non>

**Additional context**
<non>

**Comment by BuIlDaLiBlE** [comment]
The aim of the launcher is to do everything for the user, so I don't really see how this would fit.
