### ISSUE TITLE
Language contibution [english]

### ISSUE THREAD

**Issue by corruption111** [BuIlDaLiBlE/BetterHI3Launcher#11]
**Attach the file here**
textStrings.Add("version", "Version");
            textStrings.Add("launcher_version", "Launcher version");
            textStrings.Add("binary_prefixes", "KMGTPEZY");
            textStrings.Add("binary_prefix_byte", "b");
            textStrings.Add("bytes_per_second", "B/s");
            textStrings.Add("outdated", "Outdated");
            textStrings.Add("enabled", "Enabled");
            textStrings.Add("disabled", "Disabled");
            textStrings.Add("button_yes", "Yes");
            textStrings.Add("button_no", "No");
            textStrings.Add("button_download", "Download");
            textStrings.Add("button_downloading", "Downloading");
            textStrings.Add("button_running", "Running");
            textStrings.Add("button_update", "Update");
            textStrings.Add("button_pause", "Pause");
            textStrings.Add("button_launch", "Start");
            textStrings.Add("button_options", "Options");
            textStrings.Add("button_resume", "Resume");
            textStrings.Add("button_ok", "OK");
            textStrings.Add("button_confirm", "Confirm");
            textStrings.Add("button_cancel", "Cancel");
            textStrings.Add("button_github", "Go to GitHub repository");
            textStrings.Add("button_generate", "Generate");
            textStrings.Add("label_server", "Server");
            textStrings.Add("label_mirror", "Mirror");
            textStrings.Add("label_log", "Show log");
            textStrings.Add("contextmenu_downloadcache", "Download cache");
            textStrings.Add("contextmenu_repair", "Repair game files");
            textStrings.Add("contextmenu_move", "Move game files");
            textStrings.Add("contextmenu_uninstall", "Uninstall game");
            textStrings.Add("contextmenu_fixsubs", "Fix subtitles");
            textStrings.Add("contextmenu_download_type", "Change download type");
            textStrings.Add("contextmenu_game_settings", "Manage game settings");
            textStrings.Add("contextmenu_customfps", "Set custom FPS cap");
            textStrings.Add("contextmenu_customresolution", "Set custom resolution");
            textStrings.Add("contextmenu_resetgamesettings", "Reset game settings");
            textStrings.Add("contextmenu_web_profile", "Go to web profile");
            textStrings.Add("contextmenu_feedback", "Send feedback");
            textStrings.Add("contextmenu_changelog", "Show changelog");
            textStrings.Add("contextmenu_language", "Language");
            textStrings.Add("contextmenu_language_system", "System Default");
            textStrings.Add("contextmenu_language_english", "English");
            textStrings.Add("contextmenu_language_russian", "Russian");
            textStrings.Add("contextmenu_language_spanish", "Spanish");
            textStrings.Add("contextmenu_language_portuguese", "Portuguese");
            textStrings.Add("contextmenu_language_german", "German");
            textStrings.Add("contextmenu_language_vietnamese", "Vietnamese");
            textStrings.Add("contextmenu_language_contribute", "Want to help?");
            textStrings.Add("contextmenu_about", "About");
            textStrings.Add("progresstext_error", "Mistakes were made :^(");
            textStrings.Add("progresstext_verifying_files", "Verifying game files...");
            textStrings.Add("progresstext_verifying_file", "Verifying game file {0}/{1}...");
            textStrings.Add("progresstext_cleaningup", "Cleaning up...");
            textStrings.Add("progresstext_checkingupdate", "Checking for update...");
            textStrings.Add("progresstext_downloadsize", "Download size");
            textStrings.Add("progresstext_downloaded", "Downloaded {0}/{1} ({2})");
            textStrings.Add("progresstext_downloading_file", "Downloading file {0}/{1}...");
            textStrings.Add("progresstext_eta", "Estimated time: {0}");
            textStrings.Add("progresstext_unpacking_1", "Unpacking game files...");
            textStrings.Add("progresstext_unpacking_2", "Unpacking game file {0}/{1}...");
            textStrings.Add("progresstext_moving_files", "Moving game files...");
            textStrings.Add("progresstext_uninstalling", "Uninstalling the game...");
            textStrings.Add("progresstext_mirror_connect", "Connecting to mirror...");
            textStrings.Add("progresstext_initiating_download", "Initiating download...");
            textStrings.Add("progresstext_updating_launcher", "Updating launcher...");
            textStrings.Add("progresstext_generating_hash", "Generating hash for file {0}/{1}...");
            textStrings.Add("progresstext_zipping", "Adding file {0}/{1} to ZIP archive...");
            textStrings.Add("progresstext_fetching_hashes", "Fetching file hashes...");
            textStrings.Add("introbox_title", "Welcome to Better Honkai Impact 3rd launcher!");
            textStrings.Add("introbox_msg_1", "!!! IMPORTANT, PLEASE READ !!!");
            textStrings.Add("introbox_msg_2", "Seems like this is your first time using the launcher. First of all, I'm glad you've decided to give it a try so in case you'd like to give feedback don't hesitate to do so.\nSecondly, it is important that if you used the official launcher to update the game and didn't launch it yet (to the point where you are on the bridge) you shouldn't use this launcher. Otherwise the launcher may detect your game version as old and make you have to download it again.\n\nRead all that? Great! If you already have the game installed just press the \"Download\" button and select your game folder. The launcher will detect your game and you won't have to download it again.");
            textStrings.Add("downloadcachebox_msg", "Select whether to download full cache package or just numeric files.\nChoose \"Full cache\" if you have a problem updating event resources.\nChoose \"Numeric files\" if you have a problem updating settings.\nPlease note that there is currently no way to automatically retrieve latest cache and we have to upload it manually to a mirror.\nUsing mirror: {0}.\nCache last updated: {1}.\nCurrent mirror maintainer is {2}.");
            textStrings.Add("downloadcachebox_button_full_cache", "Full cache");
            textStrings.Add("downloadcachebox_button_numeric_files", "Numeric files");
            textStrings.Add("repairbox_msg", "This will check every game file and attempt to repair if any is broken. It could take a while.\nContinue?\nUsing mirror: {0}.\nCurrent mirror maintainer is {1}.");
            textStrings.Add("fpsinputbox_title", "Enter max FPS cap");
            textStrings.Add("fpsinputbox_label_combatfps", "FPS in-game");
            textStrings.Add("fpsinputbox_label_menufps", "FPS in menu");
            textStrings.Add("resolutioninputbox_title", "Enter custom resolution");
            textStrings.Add("resolutioninputbox_label_width", "Width");
            textStrings.Add("resolutioninputbox_label_height", "Height");
            textStrings.Add("resolutioninputbox_label_fullscreen", "Fullscreen");
            textStrings.Add("changelogbox_title", "Changelog");
            textStrings.Add("changelogbox_msg", "Better Honkai Impact 3rd Launcher has just become even better. Here's what happened:");
            textStrings.Add("aboutbox_msg", "Well it is much more advanced, isn't it? :^)\nThis project was made with hope for many captains to have a better experience with the game.\nIt is not affiliated with miHoYo and is completely open source.\nAny feedback is greatly appreciated.\nSpecial thanks to these GitHub contributors:\nSinsOfSeven - Custom resolution contribution\nProxy-E23 - Spanish language contibution\nSpookyKisuy - Portuguese language contibution\nbulawin1 - German language contribution\nKorewaLidesu - Vietnamese language contribution");
            textStrings.Add("msgbox_genericerror_title", "Error");
            textStrings.Add("msgbox_genericerror_msg", "An error occurred.\nFor more information take a look at the log.");
            textStrings.Add("msgbox_neterror_title", "Network error");
            textStrings.Add("msgbox_neterror_msg", "An error occurred while connecting to server:\n{0}");
            textStrings.Add("msgbox_verifyerror_title", "File validation error");
            textStrings.Add("msgbox_verifyerror_1_msg", "An error occurred while downloading. Please try again.");
            textStrings.Add("msgbox_verifyerror_2_msg", "An error occurred while downloading. File may be corrupt.\nContinue regardless?");
            textStrings.Add("msgbox_starterror_title", "Startup error");
            textStrings.Add("msgbox_starterror_msg", "An error occurred while starting the launcher:\n{0}");
            textStrings.Add("msgbox_launcherdownloaderror_msg", "An error occurred while downloading the launcher:\n{0}");
            textStrings.Add("msgbox_gamedownloaderror_title", "Error downloading game files");
            textStrings.Add("msgbox_gamedownloaderror_msg", "An error occurred while downloading game files.\nFor more information take a look at the log.");
            textStrings.Add("msgbox_installerror_msg", "An error occurred while installing game files.\nFor more information take a look at the log.");
            textStrings.Add("msgbox_installerror_title", "Installation error");
            textStrings.Add("msgbox_process_start_error_msg", "An error occurred while starting the process.\nFor more information take a look at the log.");
            textStrings.Add("msgbox_update_title", "Update notice");
            textStrings.Add("msgbox_install_msg", "The game is going to be installed to:\n{0}\nContinue?");
            textStrings.Add("msgbox_install_title", "Installation notice");
            textStrings.Add("msgbox_installdirerror_msg", "An error occurred while selecting game installation directory:\n{0}");
            textStrings.Add("msgbox_installdirerror_title", "Invalid directory");
            textStrings.Add("msgbox_abort_1_msg", "Are you sure you want to cancel the download and close the launcher?");
            textStrings.Add("msgbox_abort_2_msg", "Progress will not be saved.");
            textStrings.Add("msgbox_abort_3_msg", "Progress will be saved.");
            textStrings.Add("msgbox_abort_title", "Abort request");
            textStrings.Add("msgbox_registryerror_msg", "An error occurred while accessing registry.\nFor more information take a look at the log.");
            textStrings.Add("msgbox_registryerror_title", "Registry error");
            textStrings.Add("msgbox_registryempty_1_msg", "No value to be tweaked in registry exists.");
            textStrings.Add("msgbox_registryempty_2_msg", "Did you already run the game?");
            textStrings.Add("msgbox_registryempty_3_msg", "Try changing video settings in-game first (disabling fullscreen, changing video preset, etc).");
            textStrings.Add("msgbox_download_cache_1_msg", "Full cache is about to be downloaded.");
            textStrings.Add("msgbox_download_cache_2_msg", "Numeric file cache is about to be downloaded.");
            textStrings.Add("msgbox_download_cache_3_msg", "Download size: {0}.\nContinue?");
            textStrings.Add("msgbox_repair_1_msg", "The version of the game installed differs from repair information on the server. Due to us having to update this information manually, it may not be available for some time.\nPlease try again later.");
            textStrings.Add("msgbox_repair_2_msg", "No files need any repairs.");
            textStrings.Add("msgbox_repair_3_msg", "Found {0} corrupted/missing file(s). They need to be repaired by downloading them again.\nBecause technology is awesome, only the required files will be downloaded.\nDownload size: {1}.\nContinue?");
            textStrings.Add("msgbox_repair_4_msg", "{0} file(s) successfully repaired.");
            textStrings.Add("msgbox_repair_5_msg", "{0} file(s) failed to be repaired. Consider checking your storage device, it may be faulty.");
            textStrings.Add("msgbox_repair_6_msg", "Going to generate a JSON file containing the list of game files and their hashes, then create a ZIP archive with those files.\nContinue?");
            textStrings.Add("msgbox_move_1_msg", "The game is going to be moved to:\n{0}\nContinue?");
            textStrings.Add("msgbox_move_2_msg", "Cannot move the game inside the current game directory.");
            textStrings.Add("msgbox_move_3_msg", "Cannot move the game while the launcher is inside game directory. Move launcher outside the directory and try again.");
            textStrings.Add("msgbox_move_title", "Move");
            textStrings.Add("msgbox_move_error_title", "Move error");
            textStrings.Add("msgbox_uninstall_1_msg", "Are you sure you want to uninstall the game?");
            textStrings.Add("msgbox_uninstall_2_msg", "Are you really sure you want to uninstall the game? :^(");
            textStrings.Add("msgbox_uninstall_3_msg", "Remove game cache files and settings as well?");
            textStrings.Add("msgbox_uninstall_4_msg", "Cannot uninstall the game while the launcher is inside game directory. Move launcher outside the directory and try again.");
            textStrings.Add("msgbox_uninstall_title", "Uninstall");
            textStrings.Add("msgbox_uninstallerror_msg", "An error occurred while uninstalling the game:\n{0}");
            textStrings.Add("msgbox_uninstallerror_title", "Uninstallation error");
            textStrings.Add("msgbox_download_type_1_msg", "This will change game's resource download type in an attempt to fix the infamous update loop which doesn't let you enter the game.\nIf this doesn't fix the problem, try again.\nContinue?");
            textStrings.Add("msgbox_download_type_2_msg", "ResourceDownloadType value before: {0}.\nResourceDownloadType value after: {1}.");
            textStrings.Add("msgbox_fixsubs_1_msg", "This will attempt to fix CG subtitles (and gacha banners). Make sure you have already downloaded all CGs in the game.\nContinue?");
            textStrings.Add("msgbox_fixsubs_2_msg", "Unpacking subtitle file {0}/{1}...");
            textStrings.Add("msgbox_fixsubs_3_msg", "Checking subtitle file {0}/{1}...");
            textStrings.Add("msgbox_fixsubs_4_msg", "Unpacked subtitles for {0} CGs.");
            textStrings.Add("msgbox_fixsubs_5_msg", "Fixed {0} subtitle files.");
            textStrings.Add("msgbox_fixsubs_6_msg", "No subtitle files were fixed. They are either not downloaded yet or already fixed.");
            textStrings.Add("msgbox_customfps_1_msg", "Values must not be empty.");
            textStrings.Add("msgbox_customfps_2_msg", "Values must not be zero or negative.");
            textStrings.Add("msgbox_customfps_3_msg", "Values lower than 30 are not recommended. Continue?");
            textStrings.Add("msgbox_customfps_4_msg", "In-game and menu FPS cap successfully set to {0} and {1} respectively.");
            textStrings.Add("msgbox_customresolution_1_msg", "Height being greater than width is not recommended.\nContinue?");
            textStrings.Add("msgbox_customresolution_2_msg", "Resolution successfully set to {0}x{1} with fullscreen {2}.");
            textStrings.Add("msgbox_resetgamesettings_1_msg", "This will wipe all game settings stored in registry.\nOnly use this if you are having problems with the game!\nContinue?");
            textStrings.Add("msgbox_resetgamesettings_2_msg", "This action is irreversible. Are you sure you want to do this?");
            textStrings.Add("msgbox_resetgamesettings_3_msg", "Game settings have been wiped from registry.");
            textStrings.Add("msgbox_extractskip_title", "File skip notice");
            textStrings.Add("msgbox_extractskip_msg", "Unpacking finished, but some files failed to be unpacked. You might want to unpack them manually.\nFor more information take a look at the log.");
            textStrings.Add("msgbox_noexe_title", "No game executable");
            textStrings.Add("msgbox_noexe_msg", "Game executable cannot be found.\nTry reinstalling the game.");
            textStrings.Add("msgbox_nodir_title", "No game directory");
            textStrings.Add("msgbox_nodir_msg", "Game directory cannot be found.\nTry reinstalling the game.");
            textStrings.Add("msgbox_installexisting_msg", "The game appears to have already been installed to:\n{0}\nUse this directory?");
            textStrings.Add("msgbox_installexistinginvalid_msg", "The selected directory doesn't contain a valid installation of the game. This launcher only supports Global and SEA clients.");
            textStrings.Add("msgbox_install_existing_no_local_version_msg", "Local version couldn't be determined.\nIs your game updated already? Please choose wisely!\nSelecting \"Yes\" will make you be able to launch the game.\nSelecting \"No\" will make you have to download the game.");
            textStrings.Add("msgbox_notice_title", "Notice");
            textStrings.Add("msgbox_novideodir_msg", "Video directory cannot be found.\nTry reinstalling the game.");
            textStrings.Add("msgbox_mirrorinfo_msg", "Use this mirror only if you cannot download the game via official miHoYo servers.\nPlease note that it is updated manually.\nContinue?");
            textStrings.Add("msgbox_updatecheckerror_msg", "An error occurred while checking for update.\nFor more information take a look at the log.");
            textStrings.Add("msgbox_updatecheckerror_title", "Update check error");
            textStrings.Add("msgbox_gamedownloadmirrorold_msg", "It seems like the game version on miHoYo servers is newer than the one on the mirror.\nThere is no reason to download an outdated version, ask the mirror maintainer to upload a new version.");
            textStrings.Add("msgbox_gamedownloadpaused_msg", "The game is not downloaded entirely yet. Changing server or mirror will reset the download progress.\nContinue?");
            textStrings.Add("msgbox_gamedownloadmirrorerror_msg", "An error occurred while downloading from the mirror.\nFor more information take a look at the log.");
            textStrings.Add("msgbox_install_little_space_msg", "There is potentially not enough free space on selected device, it is recommended to free up some space or installation may result in failure.\nContinue?");
            textStrings.Add("msgbox_install_wrong_drive_type_msg", "Cannot install on selected device.");
            textStrings.Add("msgbox_move_little_space_msg", "There is potentially not enough free space on selected device, it is recommended to free up some space or move operation may result in failure.\nContinue?");
            textStrings.Add("msgbox_move_wrong_drive_type_msg", "Cannot move to selected device.");
            textStrings.Add("msgbox_mirror_error_msg", "There's an error with the mirror. Ask the mirror maintainer to get to the bottom of this.\nMessage: {0}");
            textStrings.Add("msgbox_net_version_old_msg", "This launcher requires .NET Framework 4.6.1 or newer to be installed.");
            textStrings.Add("msgbox_language_msg", "Language is going to be changed to {0} and launcher will be restarted.\nContinue?");
            textStrings.Add("msgbox_no_internet_msg", "Cannot connect to the internet. Are you online?");

**Comment by BuIlDaLiBlE** [comment]
But... launcher's primary language is already English 😐
Can you elaborate on what you tried to do?

**Comment by BuIlDaLiBlE** [comment]
Closed due to lack of activity.
