### ISSUE TITLE
High GPU Usage

### ISSUE THREAD

**Issue by tizoy12** [BuIlDaLiBlE/BetterHI3Launcher#12]
![image](https://user-images.githubusercontent.com/62270450/114485283-3a014800-9c3e-11eb-9670-562c338c396f.png)

**Comment by bulawin1** [comment]
Same here

**Comment by BuIlDaLiBlE** [comment]
It's a known issue because of the DropShadowEffect. Minimizing the launcher lowers the usage, but you can disable the effect completely by specifying `NOSHADOW` command line argument.

**Comment by BuIlDaLiBlE** [comment]
Addressed in [v1.1.20210511.0](https://github.com/BuIlDaLiBlE/BetterHI3Launcher/releases/tag/1.1.20210511.0), now it uses a static image instead (took my time to extract official launcher assets).
