### ISSUE TITLE
touch support in game for surface devices

### ISSUE THREAD

**Issue by LegacyGamerHD** [BuIlDaLiBlE/BetterHI3Launcher#13]
**Is your feature request related to a problem? Please describe.**
i would like way to just use touchscreen in game

**Describe the solution you'd like**
that i cn play with touch controls

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by LegacyGamerHD** [comment]
stupid id i need as ask somewere esle probely

**Comment by BuIlDaLiBlE** [comment]
I can't quite grasp what exactly do you mean. Is the launcher not usable with touch controls? You also mentioned the game itself which I can't do anything about.

**Comment by SBTGAMING** [comment]
Hi lacgacyGamerHD
Please help me to fix PojavLauncher Zink Version
My Phone it not work it exit the game
