### ISSUE TITLE
Download Cache returns 404 error

### ISSUE THREAD

**Issue by Zero-Starlight** [BuIlDaLiBlE/BetterHI3Launcher#14]
**Describe the bug**
Attempts to download cache return the following:
Fetching mirror data...
ERROR: Failed to fetch MediaFire file metadata:
The remote server returned an error: (404) Not Found.

**To Reproduce**
1. Go to 'Options'
2. Click on 'Download Cache'

**Expected behavior**
Launcher downloads cache.

**Log**

**Screenshots**
![image](https://user-images.githubusercontent.com/29644943/115744228-5f8a0200-a360-11eb-91da-35d52f317818.png)

**Desktop (please complete the following information):**
* OS: Windows 10 Pro Edition, 64 Bit Version	10.0.19042 Build 19042
* Launcher version 1.1.20210419.1

**Comment by BuIlDaLiBlE** [comment]
There was an update today, so the mirror maintaner guy got rid of old files - new ones will be uploaded later today.
