### ISSUE TITLE
Option to view the first run tutorial again

### ISSUE THREAD

**Issue by Zero-Starlight** [BuIlDaLiBlE/BetterHI3Launcher#15]
**Is your feature request related to a problem? Please describe.**
Since the information provided is described as being important, it probably shouldn't be made impossible to review if needed down the line.

**Describe the solution you'd like**
A simple menu option to open the window again would probably suffice.

**Comment by BuIlDaLiBlE** [comment]
Addressed in [v1.1.20210424.0](https://github.com/BuIlDaLiBlE/BetterHI3Launcher/releases/tag/1.1.20210424.0). Thanks for your suggestion!
