### ISSUE TITLE
No network error upon first run

### ISSUE THREAD

**Issue by minh2134** [BuIlDaLiBlE/BetterHI3Launcher#16]
**Describe the bug**
Executing BetterHI3Launcher.exe results in "network error", regardless of user internet status. Official launcher and the game works fine.

**To Reproduce**
1. Download release v1.1.20210419.1
2. Save it anywhere
3. Click on BetterHI3Launcher.exe

**Expected behavior**

**Log**
Tried firing the launcher using Powershell, no log output.

**Screenshots**
![ảnh](https://user-images.githubusercontent.com/45842971/115904940-990d5b00-a48f-11eb-9c3b-c3c1674a5ebf.png)

**Desktop (please complete the following information):**
* OS: Windows 10
* Launcher version v1.1.20210419.1

**Additional context**
Vietnam locale.
Tried putting it on Desktop and D:\ (not OS drive), still consistent error behavior.

**Comment by BuIlDaLiBlE** [comment]
Seems like you cannot reach my servers. Can you access https://bpnet.host or https://serioussam.ucoz.ru? If not, then unfortunately you'll need to use some kind of proxy server or even a VPN.

**Comment by minh2134** [comment]
The first one I can't ping it but when I access it using Firefox I'm left with this :
![ảnh](https://user-images.githubusercontent.com/45842971/115905853-e50ccf80-a490-11eb-9e78-14cfe2bc573a.png)

The second one I can ping it just fine.

**Comment by BuIlDaLiBlE** [comment]
Hmm, not sure what can be the problem. Can you try this build and show me what it outputs?
[BetterHI3Launcher_1.1.20210423.0_TEST.zip](https://github.com/BuIlDaLiBlE/BetterHI3Launcher/files/6367127/BetterHI3Launcher_1.1.20210423.0_TEST.zip)

**Comment by minh2134** [comment]
![ảnh](https://user-images.githubusercontent.com/45842971/115909441-bcd39f80-a495-11eb-880e-11f3fb20173f.png)
This one gives more insight into the problem. It gives the same output as https://bpnet.host when I try to ping it in powershell.

**Comment by BuIlDaLiBlE** [comment]
Ah, so the problem lies connecting to miHoYo servers. Since the launcher uses Global servers by default it tries to connect to them but fails. This is something I was aware of but didn't do anything about. Can you try applying this registry file and running  the launcher again?
[bbh3l_os_reg.zip](https://github.com/BuIlDaLiBlE/BetterHI3Launcher/files/6367181/bbh3l_os_reg.zip)

**Comment by minh2134** [comment]
Ah that works. Though I am a Global player and my official launcher + game works fine.
![ảnh](https://user-images.githubusercontent.com/45842971/115911444-4c7a4d80-a498-11eb-98ab-e55f11ef5cde.png)
Here's the error log when I tried to switch to global server on the program.

**Comment by BuIlDaLiBlE** [comment]
Hm, that's surely weird. The timeout I set is 30 seconds which is more than enough time to reliably say the connection isn't going to be established. How long does it take for the official launcher to open? How fast does this URL open: https://d2wztyirwsuyyo.cloudfront.net/tmp/com.miHoYo.bh3global/pc/VersionInfo.txt?

**Comment by minh2134** [comment]
Definitely within in 5s for me to open up that link.

**Comment by BuIlDaLiBlE** [comment]
Honestly, I have no idea at this point. This just doesn't make any sense.

**Comment by KorewaLidesu** [comment]
Did you run the game with admin perm?

**Comment by minh2134** [comment]
Yeah, that's a given since the program requires admin perm by default.
