### ISSUE TITLE
Nothing on startup

### ISSUE THREAD

**Issue by Yrbaaa** [BuIlDaLiBlE/BetterHI3Launcher#17]
**Describe the bug**
After downloading and launching nothing pops up however a process is present in task manager and after a minute or two it shuts down.

**To Reproduce**
1. Just run the executable

**Expected behavior**
A window to pop up

**Log**
---

**Screenshots**
---

**Desktop (please complete the following information):**
* OS: Windows 10 64x
* Launcher version [v1.1.20210426.1]

**Additional context**
-App is run with adminstrator rights.

**Comment by BuIlDaLiBlE** [comment]
Happens to me randomly during development as well. Killing the process and starting again always works but I've been curious of the true cause. Though it seems like even restarting like that doesn't fix it for some people. Will need to investigate this.

**Comment by Yrbaaa** [comment]
Killing the process and launching the app again doesn't do anything to me still nothing. If there is any kind of log or smth I could provide just point me to the right direction.

**Comment by BuIlDaLiBlE** [comment]
Actually, there is a log file now since a recent release, but I bet it wouldn't be of much help until I make a debug build.
It's located at `%userprofile%\AppData\LocalLow\Bp\Better HI3 Launcher`

**Comment by Yrbaaa** [comment]
For me the location "\Bp\Better HI3 Launcher" doesn't even exist.

**Comment by BuIlDaLiBlE** [comment]
Aha, so that was the problem. Create that directory - it should make the launcher start. I'll fix that in the next update...

**Comment by Yrbaaa** [comment]
Yeah that's right! Creating those two directories fixed it, now the launcher starts normally! Thanks for the help.

**Comment by BuIlDaLiBlE** [comment]
Addressed in [v1.1.20210428.0](https://github.com/BuIlDaLiBlE/BetterHI3Launcher/tree/1.1.20210428.0).
