### ISSUE TITLE
Not launching

### ISSUE THREAD

**Issue by Marduken** [BuIlDaLiBlE/BetterHI3Launcher#18]
It just doesn't launch at all. I even had Task Manager open just to see what exactly happens. It tries to launch for a split second and immediately crashes and opens Windows Problem Reporting tab (though all this still doesn't even appear on the screen).

Edit: I also have it excluded from Windows Defender and am running it as administrator.

**Comment by BuIlDaLiBlE** [comment]
Duplicate of #17, try the temporary solution there. I'll fix the issue with the next update.
