### ISSUE TITLE
Mesa_Dev_Test it crash my phone

### ISSUE THREAD

**Issue by SBTGAMING** [BuIlDaLiBlE/BetterHI3Launcher#20]
Lasttest.log

--------- beggining with launcher debug
Info: Launcher version: 3.3.1.1_rel_20210418
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64/aarch64
Info: Custom Java arguments: "-Xms512m -Xmx800m -Dorg.lwjgl.opengl.libname=libOSMesa_8.so"
Headless version detected! (20200910)
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so" unused DT entry: type 
0xf arg 0x361
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so" unused DT entry: type 0xf arg 0x450
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so
" unused DT entry: type 0xf arg 0x33c0
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so" unused DT entry: type 0xf arg 0x13b8
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so" unused DT entry: type 0xf arg 0x2196
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so
" unused DT entry: type 0xf arg 0x6a68
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so" unused DT entry: type 0xf arg 0x4d9
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so" unused DT entry: type 
0xf arg 0xda0
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjpeg.so" unused DT entry: type 0xf arg 0x5e6
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjpeg.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjawt.so" unused DT entry: type 0xf arg 0x77
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjawt.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjdwp.so" unused DT entry: type 0xf arg 0x1c7
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjdwp.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so" unused DT entry: type 0xf arg 0x8ff
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so" unused DT entry: type 0xf arg 0x16fe
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pcsc.so" unused DT entry: type 0xf arg 0x2e6
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pcsc.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava_crw_demo.so" unused DT entry: type 0xf arg 0xe6
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava_crw_demo.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsound.so" unused DT entry: type 0xf arg 0x119
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsound.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libunpack.so" unused DT entry: type 0xf arg 0x364
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libunpack.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsdt.so" unused DT entry: type 0xf arg 0x139
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsdt.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pkcs11.so" unused DT entry: type 0xf arg 
0xf13
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pkcs11.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/liblcms.so" unused DT entry: type 0xf arg 0x3f1
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/liblcms.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmlib_image.so" unused DT entry: type 0xf arg 0x158
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmlib_image.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libsctp.so" unused DT entry: type 0xf arg 0x6af
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libsctp.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libdt_socket.so" unused DT entry: type 0xf arg 0x1c1
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libdt_socket.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2gss.so
" unused DT entry: type 
0xf
 arg 0x6c1
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2gss.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libtinyiconv.so" unused DT entry: type 0xf arg 0x23a
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libtinyiconv.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjaas_unix.so" unused DT entry: type 
0xf arg 0x103
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjaas_unix.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libhprof.so" unused DT entry: type 0xf arg 0x1d2
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libhprof.so" has unsupported flags DT_FLAGS_1=0x81
OpenJDK 64-Bit Server VM warning: 
No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
[12:53:52] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[12:53:52] [Render thread/INFO]: Setting user: GGKH
[12:53:53] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[12:53:53] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[12:53:53] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[12:53:56] [Render thread/WARN]: Skipping bad option: textBackgroundOpacity:
[12:53:56] [Render thread/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT
OSMDroid: using developer libOSMesa.so.8 instead of built-in
OSMDroid: width=1464;height=720, reserving 4216320 bytes for frame buffer
OSMDroid: created frame buffer
OSMDroid: generating context

**Comment by BuIlDaLiBlE** [comment]
I think you're confusing this project with something else =\

**Comment by khanhduytran0** [comment]
> I think you're confusing this project with something else =\

He was thrown the log to wrong repository :trollface:

**Comment by SavagePy10** [comment]
😂😂😂😂😂😂😂😂😂😂😂😂

**Comment by SavagePy10** [comment]
Very funny

**Comment by SBTGAMING** [comment]
What is wrong?

**Comment by SBTGAMING** [comment]
This my lastest.log
--------- beggining with launcher debug
Info: Launcher version: 3.3.1.1_rel_20210415
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64/aarch64
Info: Custom Java arguments: "-Xms768m -Xmx800m -Xms1024m -Xmx2048m -Dorg.lwjgl.opengl.libname3libOSMesa_8.so -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy"
Headless version detected! (20210504)
WARNING: linker: 
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so" unused DT entry: type 0xf arg 0x361
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so" unused DT entry: type 0xf arg 0x450
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so" unused DT entry: type 0xf arg 0x33c0
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so" unused DT entry: type 0xf arg 0x13b8
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so" unused DT entry: type 0xf arg 0x2196
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so" unused DT entry: type 0xf arg 0x6a68
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so" unused DT entry: type 0xf arg 0x4d9
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so" unused DT entry: type 0xf arg 0xda0
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjpeg.so" unused DT entry: type 0xf arg 0x5e6
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjpeg.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjawt.so" unused DT entry: type 0xf arg 0x77
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjawt.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjdwp.so" unused DT entry: type 0xf arg 0x1c7
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjdwp.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so" unused DT entry: type 0xf arg 0x8ff
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so" unused DT entry: type 
0xf arg 0x16fe
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pcsc.so" unused DT entry: type 0xf arg 0x2e6
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pcsc.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava_crw_demo.so" unused DT entry: type 0xf arg 0xe6
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava_crw_demo.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsound.so" unused DT entry: type 0xf
 arg 0x119
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsound.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libunpack.so" unused DT entry: type 0xf arg 0x364
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libunpack.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsdt.so" unused DT entry: type 0xf arg 0x139
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsdt.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pkcs11.so" unused DT entry: type 0xf arg 0xf13
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pkcs11.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/liblcms.so" unused DT entry: type 0xf arg 0x3f1
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/liblcms.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmlib_image.so" unused DT entry: type 0xf arg 0x158
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmlib_image.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libsctp.so" unused DT entry: type 0xf arg 0x6af
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libsctp.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libdt_socket.so" unused DT entry: type 0xf arg 0x1c1
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libdt_socket.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2gss.so" unused DT entry: type 0xf arg 0x6c1
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2gss.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libtinyiconv.so" unused DT entry: type 0xf arg 0x23a
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libtinyiconv.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjaas_unix.so" unused DT entry: type 0xf arg 0x103
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjaas_unix.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libhprof.so" unused DT entry: type 0xf arg 0x1d2
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libhprof.so" has unsupported flags DT_FLAGS_1=0x81
OpenJDK 64-Bit Server VM warning: 
No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
OpenJDK 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
[05:52:03] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[05:52:03] [main/INFO]: Using primary tweak class name optifine.OptiFineTweaker
[05:52:03] [main/INFO]: Calling tweak class optifine.OptiFineTweaker
OptiFineTweaker: acceptOptions

OptiFineTweaker: injectIntoClassLoader
OptiFine ClassTransformer
OptiFine ZIP file: /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/optifine/OptiFine/1.16.3_HD_U_G5/OptiFine-1.16.3_HD_U_G5.jar
OptiFineTweaker: getLaunchArguments

OptiFineTweaker: getLaunchTarget
[05:52:05] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[05:52:07] [main/INFO]: [OptiFine] (Reflector) Field not found: World.tileEntitiesToBeRemoved
[05:52:08] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.eventbus.api.Event$Result
[05:52:08] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.hasTileEntity
[05:52:08] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeEntity
[05:52:08] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.CrashReportExtender
[05:52:35] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.ForgeHooksClient
[05:52:37] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[05:52:37] [main/INFO]: Setting user: IG GAM
[05:52:38] [main/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[05:52:38] [main/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[05:52:38] [main/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[05:52:39] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.settings.KeyConflictContext
[05:52:40] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.settings.KeyModifier
[05:52:40] [main/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT
OSMDroid: using built-in libOSMesa_8.so
OSMDroid: unable to load: dlopen failed: library "libOSMesa_8.so" wasn't loaded and RTLD_NOLOAD prevented it
--------- beginning of main
[0504/125245.134970:ERROR:elf_dynamic_array_reader.h(61)] tag not found
[0504/125245.190374:ERROR:elf_dynamic_array_reader.h(61)] tag not found

**Comment by SBTGAMING** [comment]
Please help solve

**Comment by SBTGAMING** [comment]
![Uploading Screenshot_2021-05-04-12-50-06-43.jpg…]()

**Comment by SBTGAMING** [comment]
![Uploading Screenshot_2021-05-04-12-50-20-75.jpg…]()

**Comment by SBTGAMING** [comment]
![Uploading Screenshot_2021-05-04-12-50-25-39.jpg…]()

**Comment by SBTGAMING** [comment]
What the f*uk
