### ISSUE TITLE
I can't do anything after launching the app

### ISSUE THREAD

**Issue by yohai13** [BuIlDaLiBlE/BetterHI3Launcher#22]
I decided to change the mirror, in search of a solution to the update problem, but now the launcher does not allow me to change anything and shows an error

1. Open BHI3Launcer
2. See error

Log
BetterHI3Launcher v1.1.20210513.0
Working directory: D:\Games\Honkai Impact 3rd
OS version: Windows 10 Pro (Version 20H2, Build 19042.985)
OS language: ru-RU
Launcher language: ru
Using server: Global
Using mirror: MediaFire
Background image 210425194255.png exists, using it
Checking for game update...

![image](https://user-images.githubusercontent.com/84676881/119268492-f403b080-bbfb-11eb-9708-6ec69ef67db6.png)

**Comment by BuIlDaLiBlE** [comment]
Даже ошибку в логе не пишет? Очень странно, я даже и не знаю что может быть не так.

**Comment by yohai13** [comment]
> Даже ошибку в логе не пишет? Очень странно, я даже и не знаю что может быть не так.
Возможно дело в ограничении доступа к MediaFire моим провайдером, попробую с впн или прокси

**Comment by yohai13** [comment]
> > Даже ошибку в логе не пишет? Очень странно, я даже и не знаю что может быть не так.
> 
> Возможно дело в ограничении доступа к MediaFire моим провайдером, попробую с впн или прокси

Yep, через впн спокойно проверились обновления и удалось сменить зеркало!
