### ISSUE TITLE
Config.ini please fix

### ISSUE THREAD

**Issue by kurosakijin** [BuIlDaLiBlE/BetterHI3Launcher#23]
Shows update button even I already updated it.

![image](https://user-images.githubusercontent.com/84918504/119839248-9bebe780-bf36-11eb-9a71-8292308c3778.png)

As for the new launcher introduced the config.ini file is different

![image](https://user-images.githubusercontent.com/84918504/119839407-b9b94c80-bf36-11eb-9783-554985ff0b63.png)

**Comment by BuIlDaLiBlE** [comment]
Close launcher, run this in command prompt and then select the game folder again.
```reg delete "HKCU\SOFTWARE\Bp\Better HI3 Launcher" /v VersionInfoSEA /f```

**Comment by BuIlDaLiBlE** [comment]
Addressed in [v1.2.20210528.0](https://github.com/BuIlDaLiBlE/BetterHI3Launcher/releases/tag/1.2.20210528.0).
