### ISSUE TITLE
Wrong Subtitle for 2.9_CG05

### ISSUE THREAD

**Issue by DragooMind** [BuIlDaLiBlE/BetterHI3Launcher#25]
**Is your feature request related to a problem? Please describe.**
2.9_CG05_mux has a completely wrong Sub which is exactly the same as the sub from 2.9_CG04. The game always downloads the wrong subtitle for this CG.

**Describe alternatives you've considered**

I am not sure how your Launcher works but I have transcibed the chinese hardsubs from the CN CG and used MTL to translate them and create my own en subfile. While the accuracy is probably somewhat questionable its still better then the completely wrong ones there are now. If your launcher can swap files then it would just swap the existing wrong sub with the replacement one.

**Additional context**

[2.9_CG05_mux_en.txt](https://github.com/BuIlDaLiBlE/BetterHI3Launcher/files/6643343/2.9_CG05_mux_en.txt)
(files has to be swapped to srt again)
If you want I can instead just give you the CN transcription so you may get more accurate subs from more professional translators.

**Comment by BuIlDaLiBlE** [comment]
What server are you on? 2.9_CG05_mux_en.srt seems totally fine to me. Here's what's in my file:
```
1
00:00:00,250 --> 00:00:01,500
Bronya: What's happening?

2
00:00:03,300 --> 00:00:06,250
Fu Hua: Still disturbed by 
your nightmares?

3
00:00:07,800 --> 00:00:10,550
Bronya: Class Monitor, the ability to
invade the private memories of others...

4
00:00:10,800 --> 00:00:12,825
Bronya: ...is nothing to be proud of.

5
00:00:13,425 --> 00:00:14,575
Bronya: But...

6
00:00:14,900 --> 00:00:15,750
Bronya: ...Spasiba.

7
00:00:16,175 --> 00:00:19,350
Gray Serpent: Hmm. How did you
get in here?

8
00:00:19,700 --> 00:00:22,450
Gray Serpent: It matters not, Bronya.

9
00:00:22,600 --> 00:00:25,050
Gray Serpent: No one can save you now.
```

**Comment by DragooMind** [comment]
I am on Global. So its probably a problem with Global in general. I saw a streamer with the same bug.

**Comment by BuIlDaLiBlE** [comment]
I'm generally not a fan of hardcoded solutions, so seems to need more info, something's not right here. If you download the original sub, what is its modification date?

**Comment by DragooMind** [comment]
If I delete the CG and Subs and redownload I get this Zip
[2.9_CG05_mux.zip](https://github.com/BuIlDaLiBlE/BetterHI3Launcher/files/6643675/2.9_CG05_mux.zip)
The modification date of the subs itself is 14.12.2020 12:02

**Comment by DragooMind** [comment]
This problem is btw consistent between both PC and Mobile client

**Comment by BuIlDaLiBlE** [comment]
Hrm, that is interesting. My file is from April 2019, perhaps they've changed something. Alright, I'll keep this case in mind for the future subtitle fixer enhancements!

**Comment by BuIlDaLiBlE** [comment]
Oh and also, are there any other files with such a problem that you know? If it doesn't trouble you, wanna take a look at all of them? Don't need to do this right away, but it will surely help.

**Comment by DragooMind** [comment]
Thats the only case I have encountered thus far. I am in the process of going through the mainstory and chronicles rn so if I notice some other cases like this I will add them here.

**Comment by DragooMind** [comment]
For 3.0_CG10_mux_1 the subtitles have a wrong name so they dont show. Each of the 4 subfiles are named 3.0_CG010_mux_1 so they dont get played.
[3.0_CG10_mux_1.zip](https://github.com/BuIlDaLiBlE/BetterHI3Launcher/files/6687947/3.0_CG10_mux_1.zip)

**Comment by DragooMind** [comment]
[3.2_CG05_mux_1.zip](https://github.com/BuIlDaLiBlE/BetterHI3Launcher/files/6697472/3.2_CG05_mux_1.zip)
3.2_CG05_mux_1 has the same problem as 2.9_CG05_mux. The subtitles are from same as the previous CG missing correct subs.

**Comment by DragooMind** [comment]
[3.6CG_08_mux_3.zip](https://github.com/BuIlDaLiBlE/BetterHI3Launcher/files/6720415/3.6CG_08_mux_3.zip)
3.6CG_08_mux_3 is another case of wrong file name. The subfiles mis the _3 so they dont get played.

**Comment by DragooMind** [comment]
[4.4CG_04_mux_0D243C6E5E5DE5E8.zip](https://github.com/BuIlDaLiBlE/BetterHI3Launcher/files/6812898/4.4CG_04_mux_0D243C6E5E5DE5E8.zip)
4.4CG_04_mux_0D243C6E5E5DE5E8 has no subs because the subs files in the zip are named "4.3CG_07_mux_0D243C6E5E5DE5E8_1" which is exaclty the same CG in a chapter before.

**Comment by BuIlDaLiBlE** [comment]
Closing due to this not being relevant anymore.
