### ISSUE TITLE
filename reverts every launch

### ISSUE THREAD

**Issue by farsdewibs0n** [BuIlDaLiBlE/BetterHI3Launcher#40]
**Describe the bug**
The filename always reverts to **BetterHI3Launcher.exe** before launch

**To Reproduce**
1. Rename the file to something else
2. Open the launcher
3. See error

**Expected behavior**
Filename should'nt be changed.

**Log**
[BetterHI3Launcher-latest.log](https://github.com/BuIlDaLiBlE/BetterHI3Launcher/files/7862748/BetterHI3Launcher-latest.log)

**Screenshots**

**Additional context**
I'm trying to switch the default launcher to BetterHI3Launcher because the mihoyo launcher doesn't open on my computer.

**Comment by BuIlDaLiBlE** [comment]
This is intended. Do not change the filename, you can hide the executable in some folder and make a shortcut to it, then change the shortcut's name.
