### ISSUE TITLE
120FPS Menu not working on new game version

### ISSUE THREAD

**Issue by tamdragonz** [BuIlDaLiBlE/BetterHI3Launcher#41]
120FPS Menu not working on new game version
![z](https://user-images.githubusercontent.com/61646515/149573886-ec33b99c-9d63-49b1-b3b2-0f3a7abc8423.png)

**Comment by BuIlDaLiBlE** [comment]
Addressed in [v1.3.20220116.0](https://github.com/BuIlDaLiBlE/BetterHI3Launcher/releases/tag/1.3.20220116.0).
