### ISSUE TITLE
How do I execute the app?

### ISSUE THREAD

**Issue by FoxPlaysGenshin** [BuIlDaLiBlE/BetterHI3Launcher#43]
Hi! I need help how do I execute the app I'm really dumb and don't know much on programming I just really need help thx. (I keep getting errors soo having some help would be really great.)

**Comment by BuIlDaLiBlE** [comment]
What errors are you getting? Can you post a screenshot?

**Comment by FoxPlaysGenshin** [comment]
ok

**Comment by FoxPlaysGenshin** [comment]
![image](https://user-images.githubusercontent.com/89443882/154028068-5a28da18-f7ff-4fc9-a5bb-cf067e9dd4e1.png)

**Comment by FoxPlaysGenshin** [comment]
i don't really know what to do

**Comment by BuIlDaLiBlE** [comment]
You've downloaded the source code which is meant for developing. Grab the latest executable from [releases](https://github.com/BuIlDaLiBlE/BetterHI3Launcher/releases) instead.

**Comment by FoxPlaysGenshin** [comment]
oh alright thx
