### ISSUE TITLE
[Bug] config.ini not generated causing official launcher to redownload the game

### ISSUE THREAD

**Issue by bagusnl** [BuIlDaLiBlE/BetterHI3Launcher#45]
**Describe the bug**
Official launcher refuses to recognize the game files even though its there and run perfectly fine using BetterHI3Launcher until I put config.ini file (got it from friend) to the game install folder.
I made this bug report in response of the latest announcement about some part of the launcher is hosted within Russia. This might be a problem for other people that used this launcher to download and install the game and then wanted to use the official launcher.

**To Reproduce**
1. Downloaded the game 7z file from https://download-sea.mihoyo.com/download/os/BH3_v5.5.0_d8d706b74ea2_os.7z
2. Put the file to .../Games/ folder
3. Launch BetterHI3Launcher and extract the game
4. Game launched fine and no related errors happen in game
5. Open official HI3 launcher
6. Try to find game files on the ... and .../Games/ folder  produces "Game resources not found...."
7. Put config.ini file on .../Games/ folder
8. Relaunch official launcher (redo step 6 if the launcher still confused)
9. "Launch" button appeared

**Expected behavior**
BetterHI3Launcher should generate config.ini file so official launcher is compatible with the game that installed using BetterHI3Launcher.

**Log**
BetterHI3Launcher log doesn't seem to be relevant, but:
```
BetterHI3Launcher v1.3.20220116.0
Working directory: E:\GameData\HonkaiImpact3\SEA\Games\
OS version: Windows 10 Pro (Version 21H2, Build 19044.1566)
OS language: en-US
Launcher language: en (autodetect)
Using server: Global
Using mirror: miHoYo
WARNING: Failed to download background image: The process cannot access the file 'C:\Users\bagusnl_reg\AppData\LocalLow\Bp\Better HI3 Launcher\Backgrounds\306b20b127299e09041fabdd15a9d7b0_5177166905936581265.png' because it is being used by another process.success!
Checking for game update...
Ready to install the game
Switched server to SEA
Checking for game update...
Ready to install the game
Downloading background image...success!
Installation directory selected: E:\GameData\HonkaiImpact3\SEA\Games
Starting to download game archive: BH3_v5.5.0_d8d706b74ea2_os.7z (https://download-sea.mihoyo.com/download/os/BH3_v5.5.0_d8d706b74ea2_os.7z)
Validating game archive...success!
Unpacking game archive...
Disabled soundssuccess!
Writing game version info...success!
Successfully installed the game
Checking for game update...
Game version: 5.5.0
Game directory: E:\GameData\HonkaiImpact3\SEA\Games
```

**Screenshots**
[Official launcher error screen](https://media.discordapp.net/attachments/427673685026013184/948433925066334258/unknown.png)
[config.ini file location (where it should be generated)](https://media.discordapp.net/attachments/427673685026013184/948439151563390986/unknown.png)

**Additional context**
config.ini file in game installation folder contains:
```
[General]
channel=1
cps=
game_version=5.5.0
sdk_version=
sub_channel=1
```

Official launcher config file:
```
[launcher]
cps=
channel=1
sub_channel=1
game_install_path=E:/GameData/HonkaiImpact3/SEA/Games
game_dynamic_bg_name=d34f2a02c64e0ebc83703b790f067a85_1027408309859337036.png
game_dynamic_bg_md5=f3c7579d22b13b314346d52c30d02173
game_start_name=BH3.exe
is_first_exit=false
exit_type=1
speed_limit_enabled=false
```

Edit: typo

**Comment by BuIlDaLiBlE** [comment]
Addressed in [v1.3.20220302.0](https://github.com/BuIlDaLiBlE/BetterHI3Launcher/releases/tag/1.3.20220302.0).
