### ISSUE TITLE
Game unable to differentiate between SEA and Global

### ISSUE THREAD

**Issue by YuRukia** [BuIlDaLiBlE/BetterHI3Launcher#60]
Downloaded the new patch on SEA yesterday, everything was working fine. This morning, for some reason, it wanted to download it again but I didn't pay that much mind.

Unfortunately, it downloaded Global despite having SEA selected, which was a nasty shock because my account had seemingly vanished into thin air and I could no longer log in.

Uninstalling and telling it to reinstall has correctly selected the overseas version (SEA), but it should be looked at.

Correct download link. `bh3_overseas`
Starting to download game archive: BH3_v6.1.0_62c4d9d7ab65.7z (https://hk-bigfile-os-mihayo.akamaized.net/ptpublic/bh3_overseas/20221021140735_XmMWKKQ97Trzyjl9/BH3_v6.1.0_62c4d9d7ab65.7z)

Incorrect download link `bh3_global`
Starting to download game archive: BH3_v6.1.0_62c4d9d7ab65.7z (https://d2wztyirwsuyyo.cloudfront.net/ptpublic/bh3_global/20221021140604_J5bTzzVUwG2WLMm6/BH3_v6.1.0_62c4d9d7ab65.7z)

**Comment by BuIlDaLiBlE** [comment]
Yep, this was a misconfiguration on my part, sorry about that. It's been since resolved.
