### ISSUE TITLE
BetterHI3Launcher can't find the game, continuous request to download

### ISSUE THREAD

**Issue by abbaccadd0** [BuIlDaLiBlE/BetterHI3Launcher#62]
**Describe the bug**
BetterHI3Launcher can't find the game.
I install mihoyo's launcher at E:\ and the game is already downloaded.
But BetterHI3Launcher can't find it.
And if I press the Download button, BetterHI3Launcher will download game in C drive.

**To Reproduce**
1. Double click on BetterHI3Launcher.exe
2. BetterHI3Launcher cannot find the game.

**Expected behavior**
BetterHI3Launcher find and run the game.

**Log**
BetterHI3Launcher v1.3.20221030.0
Working directory: E:\Games\Honkai Impact 3\
OS version: Windows 11 Pro for Workstations (Version 22H2, Build 25272.1000)
OS language: zh-CN
Launcher language: zh-CN (autodetect)
Using server: CN
Using mirror: HoYoverse
Checking for game update...
Ready to install the game

**Screenshots**
![Snipaste_2023-01-10_15-44-01](https://user-images.githubusercontent.com/39579855/211491571-b4b19d6d-cc6d-488e-86be-6192cc46d6a8.png)

**Additional context**
-

**Comment by BuIlDaLiBlE** [comment]
Hmm, what path do you use when selecting the game installation directory?

**Comment by BuIlDaLiBlE** [comment]
Sorry, I still don't understand. Can you record a video and show what happens that way?

**Comment by abbaccadd0** [comment]
> Sorry, I still don't understand. Can you record a video and show what happens that way?

Sorry, it seems to be back to normal now.
If this problem occurs again next time, I will record a video
Anyway, thanks a lot!
