### ISSUE TITLE
Launcher need 3 times the size of update as free space

### ISSUE THREAD

**Issue by Miracutor** [BuIlDaLiBlE/BetterHI3Launcher#66]
**Describe the bug**
The launcher needs 2 times the update size when first downloading preload. But when installing the update, Launcher still needs 2 times the update size for some reason. So, in the end, I need 3 times the size of the update as free space... 

For example, update 10 GB. Space needs 20 GB. Finished downloading the 10 GB update. When trying to install it, the launcher needs 20GB for some reason. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Download preload. The launcher noted needs 2 times space.
2. Install the update. The launcher noted needs 2 times space for some reason.

**Expected behaviour**
Like the Genshin launcher, only need 2 times of update size. When installing the update, if the update already downloads only check if the free space with 1-time update size.

**Additional context**
I never used the default launcher, so I don't know if this is the default behaviour...

**Comment by BuIlDaLiBlE** [comment]
Ah I see. Did you see any error messages pop up as a separate window or in the log window?
The launcher does have a free space check, but it only serves as a warning and doesn't prevent you from proceeding.

**Comment by Miracutor** [comment]
> Ah I see. Did you see any error messages pop up as a separate window or in the log window?

No

> The launcher does have a free space check, but it only serves as a warning and doesn't prevent you from proceeding.

When you think about it, you can proceed. I never tried that so, I forgot sorry. But it is still a bug because it gives a false impression that the user doesn't have enough free space. I never tried to ignore that warning because maybe I am mistaken.

**Comment by BuIlDaLiBlE** [comment]
I'll look into it, thank you for the report.

**Comment by BuIlDaLiBlE** [comment]
Having investigated it, I've come to the conclusion that the check is correct (if my logic is right).
Say you had 30 GB free space. You have then downloaded 10 GB, so you now have 20 GB free. The compressed archive contains 15 GB worth of files when decompressed - the actual size checked is higher to make sure there's some space to spare in case free space changes during decompression (which is very likely to happen on a system drive, for example). Remember, the archive remains there until decompression is finished - so you need to account the 10 GB it's occupying. After the decompression is done, we are left with 5 GB, then the 10 GB archive is deleted and 15 GB of free space remains.

Hopefully my logic is right, I'm all ears if I made a mistake anywhere.

**Comment by BuIlDaLiBlE** [comment]
Tweaked the installation UI to provide the archive size + recommended free space prior to decompression in [v1.4.20230628.0](https://github.com/BuIlDaLiBlE/BetterHI3Launcher/releases/tag/1.4.20230628.0) as well as having it tell the total free space on disk. The free space recommendation in pre-installation remains the same, as I believe the archive size can be disregarded because files are being mostly overwritten without taking much extra space.

If you have something to say please do otherwise I'm going to close the issue.

**Comment by Miracutor** [comment]
From my understanding of what you said, yeah, that should be fine.

I don't think I have anything more about this issue. Thanks!
