### ISSUE TITLE
BetterLauncher for HSR and GI?

### ISSUE THREAD

**Issue by yudha1aja** [BuIlDaLiBlE/BetterHI3Launcher#68]
Hi @BuIlDaLiBlE i really like betterhi3launcher. it's help me to fix slow speed update download with original launcher
with normal launcher my download speed it's slow as fck to download 11 gb update i just got 2MB/s but with Betterlauncher i get 4MB/s improved speed
so, if you can... i really love to have Betterlauncher for HSR or maybe GI too
Thank you

**Comment by BuIlDaLiBlE** [comment]
Hi! Genshin has already been suggested before (#24), however I have no plans on ever making a launcher for other HoYo games, including HSR. You can check the [Collapse](https://github.com/neon-nyan/Collapse) project, it's also a custom launcher but supports all HoYoverse games.
