### ISSUE TITLE
Probably unrelated but ...

### ISSUE THREAD

**Issue by markedone66** [BuIlDaLiBlE/BetterHI3Launcher#73]
Is there any chance you guys are gonna look at the "other honkai" aka HSR client to make a custom launcher that hacks some stuff? 

I reached out to  hoyo multiple times to let us use ultra wide on non UW screen and they just wont. So a custom launcher like honkai 3rd has fdor HSR would be absolutely epic to let me also play 2560x1080p  😭  ... I nany case sorry for creating bloat issues. Was rly just wondering what are your plans! 

Cheers for the epic launcher for HI3Rd tho! been using for a hot minute now <3

**Comment by BuIlDaLiBlE** [comment]
Sorry, no plans for that. You may wanna take a look at [CollapseLauncher](https://github.com/CollapseLauncher/CollapseLauncher) though.

**Comment by markedone66** [comment]
sorry just noticed,  thanks for the advice! :)
