### ISSUE TITLE
multi-channel sound settings as flag

### ISSUE THREAD

**Issue by kiam001** [BuIlDaLiBlE/BetterHI3Launcher#74]
**Is your feature request related to a problem? Please describe.**
I have a 5.1 surround system since a few Honkai versions Hi3 only outputs stereo which doesn't sound good anymore

**Describe the solution you'd like**
A flag to change sorround channels

**Describe alternatives you've considered**
I have already tried to use OpenAL which does not work, but maybe there is a flag that you can set to simply activate 5.1, 7.1

**Additional context**
I would be happy for a solution, I will be active for enquiries

**Comment by BuIlDaLiBlE** [comment]
Sorry, but this is something that is not related to the launcher, but to the game itself. You may contact Customer Service in-game or by email to let them know about the issue or make a suggestion. If you have any feedback about the launcher, feel free to open a new issue.
