### ISSUE TITLE
Honkai Impact Launcher Crashes Upon Pressing "Update" Button

### ISSUE THREAD

**Issue by Ysundere** [BuIlDaLiBlE/BetterHI3Launcher#76]
**Describe the bug**
Launcher shows crash window upon pressing the "Update" button.

**To Reproduce**
1. Open E:\BetterHI3Launcher.exe and [OK] on UAC prompt to elevate launcher as Admin 
2. Press "Update" button -> Crash
Note: Honkai Impact 3 folder was installed on "E:\Honkai Impact 3\" on a previous OS installation, but is preserved on a fresh OS install.
4. See error log below

**Expected behavior**
Launcher should update game directory

**Log**
If you haven't closed the launcher yet, add the output of entire log window; otherwise search for the appropriate log in this path: `%userprofile%\AppData\LocalLow\Bp\Better HI3 Launcher`.
[BetterHI3Launcher-latest.log](https://github.com/BuIlDaLiBlE/BetterHI3Launcher/files/14614947/BetterHI3Launcher-latest.log)

**Screenshots**

Launcher window:
![image](https://github.com/BuIlDaLiBlE/BetterHI3Launcher/assets/163531836/975c8f6b-bf39-4a51-b9e7-412b13a25377)

Upon pressing update button:
![image](https://github.com/BuIlDaLiBlE/BetterHI3Launcher/assets/163531836/a817f733-d065-4938-8f40-be82c067403c)

**Additional context**
n/a

**Comment by BuIlDaLiBlE** [comment]
Can you send a screenshot of your `E:\Honkai Impact 3` folder?

**Comment by BuIlDaLiBlE** [comment]
No need, I have reproduced the error and it will be fixed in the future, thank you for the report. For the time being you can use the official launcher to update the game.

**Comment by BuIlDaLiBlE** [comment]
Addressed in [v1.5.20240423.0](https://github.com/BuIlDaLiBlE/BetterHI3Launcher/releases/tag/1.5.20240423.0). Thank you for the report!
