### ISSUE TITLE
launcher not opening all of a sudden

### ISSUE THREAD

**Issue by Omegaxis8009** [BuIlDaLiBlE/BetterHI3Launcher#79]
**Describe the bug**
Updated to newest patch yesterday and played with no issues, now all of a sudden the launcher is throwing errors and not working. Game still launches fine if I directly open the game's executable.

**To Reproduce**
Open the launcher with taskbar shortcut - throws errors
Open the launcher with exe - throws errors

**Expected behavior**
The launcher to open.

**Log**
[BetterHI3Launcher-latest.log](https://github.com/user-attachments/files/17442186/BetterHI3Launcher-latest.log)

I have no idea what could have changed between yesterday and today for it to do this.

**Comment by BuIlDaLiBlE** [comment]
It looks like an issue on your end, I can't reproduce it. From the error log it mentions corrupt memory, so you need to investigate your system.
