### ISSUE TITLE
Unable to enter the game

### ISSUE THREAD

**Issue by furquim87** [BuIlDaLiBlE/BetterHI3Launcher#8]
Hey, I downloaded this custom launcher today and tried to enter the game but I'm stuck at the loading screen, receiving a message that my game is out of date.

I can enter the game just fine by using the original launcher, but when I try using this custom version I cannot go past the loading screen as I receive a notification saying "Please download the latest version! Once you sucessfuly download it, all Captains Lv,6 and above will receive 360 crystals~".

What should I do?

Thanks in advance.

**Comment by BuIlDaLiBlE** [comment]
When did you download the game? Are you sure they are both in the same directory?

**Comment by furquim87** [comment]
> 
> 
> When did you download the game? Seems like you have got two different versions somehow. Are you sure both launchers use the same directory?

I downloaded about two months ago, but there was an older installation of the game which I deleted when I stopped playing about a year ago.

And yes, it is using the same directory.

I'll have to format my PC for an unrelated reason, and I'll update you with the results after launching the game in the fresh Windows install.

**Comment by furquim87** [comment]
I formated the PC and tried again but I'm still getting the same error.

**Comment by BuIlDaLiBlE** [comment]
I'm not sure how that even happens. In that case, you likely need to download the latest version yourself.
You can do so manually here: https://bpnet.host/bh3
After that open the game and log in to the game then try my launcher again.

**Comment by furquim87** [comment]
Thanks. It seems that I've managed to do it by completely uninstalling the game using BCU and installing it using your launcher.

**Comment by BuIlDaLiBlE** [comment]
Great! I'll be closing this issue now then.
